Change folder structures, set up entities/graphql structures
trishulaorg/tenet-api-server pull request #7
Opened 2022-12-13 12:26 UTC by minamorl

## About
This PR is intended to show the basic structures to other devs.
Both QueryRoot/Mutation is correctly working under this PR.

## Issue

## Detail

## Screenshot

## URL

## Others

2022-12-17 08:08 UTC, chansuke requested changes
I've added some comments.

2022-12-17 08:08 UTC, chansuke commented on src/setup.rs
> +    let database_url: std::string::String = env::var("DATABASE_URL").unwrap();
unwrap() just panics when you failed to get the environment variable in here, so should choose another way(ex: unwrap_or_else() etc).

2022-12-17 11:24 UTC, minamorl commented on src/setup.rs
> +    let database_url: std::string::String = env::var("DATABASE_URL").unwrap();
ok tyty

2022-12-18 05:38 UTC, minamorl commented on src/main.rs
> +        let db = ctx.data::<DatabaseConnection>().unwrap();
using Context lgtm. ill make changes

2022-12-18 05:39 UTC, minamorl commented on src/main.rs
> +        let db = ctx.data::<DatabaseConnection>().unwrap();
ref https://async-graphql.github.io/async-graphql/en/context.html

2023-01-19 16:56 UTC, minamorl commented
@chansuke Can you take a look at these changes?

2023-01-19 16:59 UTC, chansuke commented
@minamorl Ok

2023-01-22 05:51 UTC, chansuke commented on entities/src/board.rs
> +pub struct Model {
The naming should be `Board` or `BoardModel`?

2023-01-22 05:52 UTC, chansuke commented on entities/src/board.rs
> +pub struct Model {
ah, > Generated by sea-orm-codegen

2023-01-22 05:58 UTC, chansuke commented on graphql/src/models.rs
> +use async_graphql::*;
You should separate this file IMHO
- graphql/src/user.rs
etc

2023-01-22 06:17 UTC, chansuke commented on graphql/src/mutations.rs
> +        let db = context.data::<DatabaseConnection>().unwrap();
remove `unwrap()`  -> let db = context.data::<DatabaseConnection>();

and use map_err() in L: 26

2023-01-22 06:19 UTC, chansuke commented on migration/README.md
> +# Running Migrator CLI
we can consider to use cargo make or Makefile(should be in another issue)

2023-01-22 06:33 UTC, chansuke commented on graphql/src/queries.rs
> +        let db = context.data::<DatabaseConnection>().unwrap();
same in here. avoid unwrap() in db connection

2023-01-22 06:41 UTC, chansuke commented on graphql/src/queries.rs
> +use anyhow;
anyhow is simple and idiomatic, but better to avoid to use in this layer IMHO.

2023-01-22 06:49 UTC, chansuke commented on src/lib.rs
> +        let database_url: std::string::String = env::var("DATABASE_URL").unwrap();
please pass lint and test...

2023-01-28 10:26 UTC, merged